name: Publish Blog Post to WordPress

on:
  push:
    branches: [main]
    paths:
      - 'content/posts/*.md'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Find latest added/modified Markdown file
        id: findfile
        run: |
          file=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^content/posts/' | grep '\.md$' | tail -n 1)
          html_file="${file%.md}.html"
          echo "MD_FILE=$file" >> $GITHUB_ENV
          echo "HTML_FILE=$html_file" >> $GITHUB_ENV
          echo "Found file: $file"
          echo "HTML file: $html_file"

      - name: Convert Markdown to HTML
        if: env.MD_FILE != ''
        run: |
          pandoc "$MD_FILE" -f markdown -t html -o "$HTML_FILE"

      - name: Publish to WordPress
        if: env.MD_FILE != ''
        uses: wearerequired/action-wordpress@v1
        with:
          wordpress_url: ${{ secrets.WP_URL }}
          wordpress_username: ${{ secrets.WP_USER }}
          wordpress_application_password: ${{ secrets.WP_APPLICATION_PASSWORD }}
          title: ${{ env.MD_FILE }}
          content_file: ${{ env.HTML_FILE }}
          status: "publish"
