name: Publish Blog Post to WordPress

on:
  push:
    branches: [main]
    paths:
      - 'content/posts/*.md'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Find latest added/modified Markdown file
        id: findfile
        run: |
          # Find last modified/added Markdown file in content/posts
          file=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^content/posts/' | grep '\.md$' | tail -n 1)
          if [ -z "$file" ]; then
            # fallback: just pick the latest file in git if diff is empty (e.g. on workflow_dispatch)
            file=$(ls -t content/posts/*.md | head -n 1)
          fi
          html_file="${file%.md}.html"
          title=$(basename "$file" .md)
          echo "MD_FILE=$file" >> $GITHUB_ENV
          echo "HTML_FILE=$html_file" >> $GITHUB_ENV
          echo "TITLE=$title" >> $GITHUB_ENV

      - name: Convert Markdown to HTML
        run: |
          pandoc "$MD_FILE" -f markdown -t html -o "$HTML_FILE"

      - name: Read HTML as output
        id: get_html
        run: |
          echo "content<<EOF" >> $GITHUB_OUTPUT
          cat "$HTML_FILE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Publish to WordPress
        uses: rtCamp/action-wordpress-publish@v1
        with:
          wordpress_url: ${{ secrets.WP_URL }}
          wordpress_user: ${{ secrets.WP_USER }}
          wordpress_password: ${{ secrets.WP_APPLICATION_PASSWORD }}
          post_title: ${{ env.TITLE }}
          post_content: ${{ steps.get_html.outputs.content }}
          post_status: 'publish'
