name: Summarize and Publish to WordPress from URL

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the page to summarize and publish'
        required: true
        type: string
      title:
        description: 'Optional title override'
        required: false
        type: string

permissions:
  contents: read

jobs:
  summarize_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 google-generativeai

      - name: Fetch page content
        id: fetch
        run: |
          python scripts/fetch_page.py "${{ github.event.inputs.url }}"

      - name: Summarize text with Gemini API
        id: summarize
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python scripts/summarize_with_gemini.py

      - name: Read summary content
        id: get_summary
        run: |
          echo "summary<<EOF" >> $GITHUB_OUTPUT
          cat summary.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Publish to WordPress via REST API
        env:
          WP_URL: ${{ secrets.WP_URL }}
          WP_USER: ${{ secrets.WP_USER }}
          WP_APPLICATION_PASSWORD: ${{ secrets.WP_APPLICATION_PASSWORD }}
        run: |
          TITLE_INPUT="${{ github.event.inputs.title }}"
          DEFAULT_TITLE=$(basename "${{ github.event.inputs.url }}")
          FINAL_TITLE="${TITLE_INPUT:-$DEFAULT_TITLE}"
          AUTH=$(echo -n "$WP_USER:$WP_APPLICATION_PASSWORD" | base64)
          curl -X POST "$WP_URL/wp-json/wp/v2/posts" \
            -H "Authorization: Basic $AUTH" \
            -H "Content-Type: application/json" \
            -d "{\"title\": \"$FINAL_TITLE\", \"content\": \"$(echo "${{ steps.get_summary.outputs.summary }}" | sed ':a;N;$!ba;s/\n/\\n/g')\", \"status\": \"publish\"}"

